Follow up to https://github.com/apache/druid/pull/18839
Newer versions of Oshi requires a bump in JNA dependency too. Without that, running quickstart
with oshi sys monitor will fail processes with the following error:

Caused by: java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/CoreFoundation$CFLocale
	at oshi.software.os.mac.MacOperatingSystem.<init>(MacOperatingSystem.java:58)
	at oshi.software.os.mac.MacOperatingSystemJNA.<init>(MacOperatingSystemJNA.java:54)
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:87)
	at oshi.util.Memoizer$1.get(Memoizer.java:65)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:76)
	at org.apache.druid.java.util.metrics.OshiSysMonitor.<init>(OshiSysMonitor.java:102)
	at org.apache.druid.java.util.metrics.OshiSysMonitor.<init>(OshiSysMonitor.java:90)

Adds a unit test that fails locally with the same error without the jna dependencies bumped up.