ServiceClient: More robust redirect handling.
Detects self-redirects, redirect loops, long redirect chains, and redirects
to unknown servers. Treat all of these cases as an unavailable service,
retrying if the retry policy allows it.

Previously, some of these cases would lead to a prompt, unretryable error. This
caused clients contacting an Overlord during a leader change to fail with error
messages like:

  org.apache.druid.rpc.RpcException: Service [overlord] redirected too many times

Additionally, a slight refactor of callbacks in ServiceClientImpl improves
readability of the flow through onSuccess.