Getting Zookeeper as a repository from Bitnami.
Getting Zookeeper from Bitnami as repository and thus solving the Zookeeper error.

Error:
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "druid-zookeeper" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
ensure CRDs are installed first

After:
NAME: druid
LAST DEPLOYED: Sat Sep 30 08:44:16 2023
NAMESPACE: druid
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES: