Update IT Dockerfile to Temurin. (#18712)
The previous image openjdk:17-slim-bullseye is deprecated, along with all openjdk images generally.

This fixes the errors in recent PRs such as:
ERROR: failed to build: failed to solve: openjdk:17-slim-bullseye: failed to resolve source metadata for docker.io/library/openjdk:17-slim-bullseye: docker.io/library/openjdk:17-slim-bullseye: not found